  logo-theme[m
* [32mmain[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/add-jsconfig[m
  [31mremotes/origin/advertisement[m
  [31mremotes/origin/automagic[m
  [31mremotes/origin/ci-no-docker[m
  [31mremotes/origin/dbp-themed[m
  [31mremotes/origin/dbp-translation-component[m
  [31mremotes/origin/demo[m
  [31mremotes/origin/demo-file-handling[m
  [31mremotes/origin/favorites-and-recent-files[m
  [31mremotes/origin/filepicker-focus-bug-30450[m
  [31mremotes/origin/icon-set-mapping[m
  [31mremotes/origin/lit2[m
  [31mremotes/origin/logo-theme[m
  [31mremotes/origin/main[m
  [31mremotes/origin/person-select-custom[m
  [31mremotes/origin/port-i18next-parser[m
  [31mremotes/origin/publish[m
  [31mremotes/origin/remove-data-table-view[m
  [31mremotes/origin/remove-sentry[m
  [31mremotes/origin/renovate/jose-5.x[m
  [31mremotes/origin/renovate/lit-3.x[m
  [31mremotes/origin/renovate/lit-3.x-lockfile[m
  [31mremotes/origin/renovate/lock-file-maintenance[m
  [31mremotes/origin/renovate/major-lerna-monorepo[m
  [31mremotes/origin/renovate/open-wc-scoped-elements-3.x[m
  [31mremotes/origin/renovate/webdav-5.x[m
  [31mremotes/origin/revert-6c632dc6[m
  [31mremotes/origin/theme-switcher-focus-50410[m
  [31mremotes/origin/tutorial[m
  [31mremotes/origin/use-npm[m
  [31mremotes/origin/wc-part[m
  [31mremotes/origin/wip-cleanup[m
