image: registry.gitlab.tugraz.at/dbp/webcomponents/common/main:v5

before_script:
  - "sed -i 's|git@gitlab.tugraz.at:dbp|../..|g' .gitmodules"
  - git submodule sync
  - git submodule update --init

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npm run build
    - npm test

linting:
  stage: test
  allow_failure: true
  script:
    - npm install
    - npm run lint