image: registry.gitlab.tugraz.at/vpu/webcomponents/common/main:v2

before_script:
  - "sed -i 's|git@gitlab.tugraz.at:VPU|../..|g' .gitmodules"
  - git submodule sync
  - git submodule update --init

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npm test
