image: registry.gitlab.tugraz.at/dbp/webcomponents/common/main:v6

before_script:
  - "sed -i 's|git@gitlab.tugraz.at:dbp|../..|g' .gitmodules"
  - git submodule sync
  - git submodule update --init

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npm test
