[project]
name = "fonts"
version = "0.1.1"
description = ""
authors = [{ name = "Christoph Reiter", email = "reiter.christoph@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "fonttools>=4.17.1,<5",
    "Brotli>=1.0.9,<2",
]

[tool.uv]
package = false

[dependency-groups]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
